/**
 * ManageSpace Auth API
 * ManageSpace Auth API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CodeDeliveryDetailsResponse { 
    /**
     * The location the code has been sent to
     */
    Destination: string;
    /**
     * The way the code was send
     */
    DeliveryMedium: string;
    /**
     * The name of the attribute
     */
    AttributeName: string;
}

