/**
 * ManageSpace Auth API
 * ManageSpace Auth API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CodeDeliveryDetailsResponse { 
    /**
     * The location the code has been sent to.
     */
    destination: string;
    /**
     * The way the code was sent.
     */
    deliveryMedium: string;
    /**
     * The name of the attribute.
     */
    attributeName: string;
}

