/**
 * ManageSpace Auth API
 * ManageSpace Auth API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ERoles = 'GA' | 'OA' | 'SA' | 'M' | 'O' | 'W' | 'SM';

export const ERoles = {
    Ga: 'GA' as ERoles,
    Oa: 'OA' as ERoles,
    Sa: 'SA' as ERoles,
    M: 'M' as ERoles,
    O: 'O' as ERoles,
    W: 'W' as ERoles,
    Sm: 'SM' as ERoles
};

