/**
 * ManageSpace Auth API
 * ManageSpace Auth API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleResponse } from './roleResponse';


export interface GetRoles200Response { 
    data?: Array<RoleResponse>;
    success?: boolean;
    error?: object;
}

