/**
 * ManageSpace Auth API
 * ManageSpace Auth API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttributeResponse } from './attributeResponse';


export interface LoginUserResponse { 
    /**
     * User ID
     */
    userId: string;
    /**
     * Array of attributes.
     */
    userAttributes: Array<AttributeResponse>;
    /**
     * User Created Date
     */
    userCreatedDate: string;
    /**
     * User Last Modified Date
     */
    userLastModifiedDate: string;
    /**
     * Whether the user is enabled or not
     */
    enabled: boolean;
    /**
     * The user status
     */
    userStatus: string;
    /**
     * ID Token
     */
    idToken: string;
    /**
     * Access Token
     */
    accessToken: string;
    /**
     * Refresh Token
     */
    refreshToken: string;
}

