/**
 * ManageSpace Auth API
 * ManageSpace Auth API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttributeResponse } from './attributeResponse';


export interface RefreshTokenResponse { 
    /**
     * Access Token
     */
    accessToken: string;
    /**
     * ID Token
     */
    idToken: string;
    /**
     * User ID
     */
    userId: string;
    /**
     * Array of attributes
     */
    userAttributes: Array<AttributeResponse>;
}

