/**
 * ManageSpace Auth API
 * ManageSpace Auth API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RefreshTokenResponse } from './refreshTokenResponse';


export interface RefreshToken200Response { 
    data?: Array<RefreshTokenResponse>;
    success?: boolean;
    error?: object;
}

