/**
 * ManageSpace Auth API
 * ManageSpace Auth API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleResponse } from './roleResponse';


export interface UserResponse { 
    /**
     * User Id
     */
    userId: string;
    /**
     * First name
     */
    firstName: string;
    /**
     * Middle name
     */
    middleName?: string;
    /**
     * Last name
     */
    lastName: string;
    /**
     * User email
     */
    email: string;
    /**
     * User mobile phone number, including country code
     */
    mobileNumber: string;
    /**
     * Org Id
     */
    orgId: string;
    /**
     * Created by
     */
    createdBy: string;
    /**
     * Updated by
     */
    updatedBy?: string;
    /**
     * Created at.
     */
    createdAt: string;
    /**
     * Updated at.
     */
    updatedAt?: string;
    /**
     * Role definitions associated with user.
     */
    roles: Array<RoleResponse>;
    /**
     * A list of sites associated with this user.
     */
    assignedSites: string;
}

